// <auto-generated />
namespace SimpleEmployeeManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migdev1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migdev1));
        
        string IMigrationMetadata.Id
        {
            get { return "201703191112160_mig-dev-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
